//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EindopdrachtCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherInfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Locale { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string MainInfo { get; set; }
        public string Temperature { get; set; }
        public string Temperature_Min { get; set; }
        public string Temperature_Max { get; set; }
    }
}
